module.exports = {
  proxies: [],
  "proxy-groups": [
    {
      "name": "✈Автоматический выбор",
      "type": "url-test",
      "proxies": [
        "placeholder",
      ],
      "url": "http://google.com/generate_204",
      "interval": 3600
    },
    {
      "name": "🔰Зарубежный трафик",
      "type": "select",
      "proxies": [
        "✈Автоматический выбор",
        "placeholder",
        "🚀Прямое подключение"
      ]
    },
    {
      "name": "⚓️其他流量",
      "type": "select",
      "proxies": [
        "🔰Зарубежный трафик",
        "✈Автоматический выбор",
        "🚀Прямое подключение"
      ]
    },
    {
      "name": "✈️Telegram",
      "type": "select",
      "proxies": [
        "🔰Зарубежный трафик",
        "✈Автоматический выбор",
        "placeholder"
      ]
    },
    {
      "name": "🎬Youtube",
      "type": "select",
      "proxies": [
        "🔰Зарубежный трафик",
        "✈Автоматический выбор",
        "placeholder"
      ]
    },
    {
      "name": "🎬Netflix",
      "type": "select",
      "proxies": [
        "🔰Зарубежный трафик",
        "✈Автоматический выбор",
        "placeholder"
      ]
    },
    {
      "name": "🎬Иностранные СМИ",
      "type": "select",
      "proxies": [
        "🔰Зарубежный трафик",
        "✈Автоматический выбор",
        "placeholder"
      ]
    },
    {
      "name": "🍎Сервисы Apple",
      "type": "select",
      "proxies": [
        "🚀Прямое подключение",
        "✈Автоматический выбор",
        "🔰Зарубежный трафик"
      ]
    },
    {
      "name": "🚀Прямое подключение",
      "type": "select",
      "proxies": [
        "DIRECT"
      ]
    }
  ],
  rules: [
    "DOMAIN-SUFFIX,smtp,DIRECT",
    "DOMAIN-KEYWORD,aria2,DIRECT",
    "DOMAIN-SUFFIX,ampproject.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,appspot.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,blogger.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,getoutline.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,gvt0.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,gvt1.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,gvt3.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,xn--ngstr-lra8j.com,🔰Зарубежный трафик",
    "DOMAIN-KEYWORD,google,🔰Зарубежный трафик",
    "DOMAIN-KEYWORD,blogspot,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,onedrive.live.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,xboxlive.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,cdninstagram.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,fb.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,fb.me,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,fbaddins.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,fbcdn.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,fbsbx.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,fbworkmail.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,instagram.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,m.me,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,messenger.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,oculus.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,oculuscdn.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,rocksdb.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,whatsapp.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,whatsapp.net,🔰Зарубежный трафик",
    "DOMAIN-KEYWORD,facebook,🔰Зарубежный трафик",
    "IP-CIDR,3.123.36.126/32,🔰Зарубежный трафик,no-resolve",
    "IP-CIDR,35.157.215.84/32,🔰Зарубежный трафик,no-resolve",
    "IP-CIDR,35.157.217.255/32,🔰Зарубежный трафик,no-resolve",
    "IP-CIDR,52.58.209.134/32,🔰Зарубежный трафик,no-resolve",
    "IP-CIDR,54.93.124.31/32,🔰Зарубежный трафик,no-resolve",
    "IP-CIDR,54.162.243.80/32,🔰Зарубежный трафик,no-resolve",
    "IP-CIDR,54.173.34.141/32,🔰Зарубежный трафик,no-resolve",
    "IP-CIDR,54.235.23.242/32,🔰Зарубежный трафик,no-resolve",
    "IP-CIDR,169.45.248.118/32,🔰Зарубежный трафик,no-resolve",
    "DOMAIN-SUFFIX,pscp.tv,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,periscope.tv,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,t.co,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,twimg.co,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,twimg.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,twitpic.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,vine.co,🔰Зарубежный трафик",
    "DOMAIN-KEYWORD,twitter,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,t.me,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,tdesktop.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,telegra.ph,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,telegram.me,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,telegram.org,🔰Зарубежный трафик",
    "IP-CIDR,91.108.4.0/22,🔰Зарубежный трафик,no-resolve",
    "IP-CIDR,91.108.8.0/22,🔰Зарубежный трафик,no-resolve",
    "IP-CIDR,91.108.12.0/22,🔰Зарубежный трафик,no-resolve",
    "IP-CIDR,91.108.16.0/22,🔰Зарубежный трафик,no-resolve",
    "IP-CIDR,91.108.56.0/22,🔰Зарубежный трафик,no-resolve",
    "IP-CIDR,149.154.160.0/20,🔰Зарубежный трафик,no-resolve",
    "IP-CIDR6,2001:b28:f23d::/48,🔰Зарубежный трафик,no-resolve",
    "IP-CIDR6,2001:b28:f23f::/48,🔰Зарубежный трафик,no-resolve",
    "IP-CIDR6,2001:67c:4e8::/48,🔰Зарубежный трафик,no-resolve",
    "DOMAIN-SUFFIX,line.me,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,line-apps.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,line-scdn.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,naver.jp,🔰Зарубежный трафик",
    "IP-CIDR,103.2.30.0/23,🔰Зарубежный трафик,no-resolve",
    "IP-CIDR,125.209.208.0/20,🔰Зарубежный трафик,no-resolve",
    "IP-CIDR,147.92.128.0/17,🔰Зарубежный трафик,no-resolve",
    "IP-CIDR,203.104.144.0/21,🔰Зарубежный трафик,no-resolve",
    "DOMAIN-SUFFIX,4shared.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,520cc.cc,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,881903.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,9cache.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,9gag.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,abc.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,abc.net.au,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,abebooks.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,amazon.co.jp,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,apigee.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,apk-dl.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,apkfind.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,apkmirror.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,apkmonk.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,apkpure.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,aptoide.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,archive.is,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,archive.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,arte.tv,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,artstation.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,arukas.io,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,ask.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,avg.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,avgle.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,badoo.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,bandwagonhost.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,bbc.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,behance.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,bibox.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,biggo.com.tw,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,binance.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,bitcointalk.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,bitfinex.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,bitmex.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,bit-z.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,bloglovin.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,bloomberg.cn,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,bloomberg.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,blubrry.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,book.com.tw,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,booklive.jp,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,books.com.tw,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,boslife.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,box.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,businessinsider.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,bwh1.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,castbox.fm,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,cbc.ca,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,cdw.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,change.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,channelnewsasia.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,ck101.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,clarionproject.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,clyp.it,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,cna.com.tw,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,comparitech.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,conoha.jp,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,crucial.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,cts.com.tw,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,cw.com.tw,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,cyberctm.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,dailymotion.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,dailyview.tw,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,daum.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,daumcdn.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,dcard.tw,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,deepdiscount.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,depositphotos.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,deviantart.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,disconnect.me,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,discordapp.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,discordapp.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,disqus.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,dlercloud.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,dns2go.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,dowjones.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,dropbox.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,dropboxusercontent.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,duckduckgo.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,dw.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,dynu.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,earthcam.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,ebookservice.tw,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,economist.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,edgecastcdn.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,edu,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,elpais.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,enanyang.my,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,encyclopedia.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,esoir.be,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,etherscan.io,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,euronews.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,evozi.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,feedly.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,firech.at,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,flickr.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,flitto.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,foreignpolicy.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,freebrowser.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,freewechat.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,freeweibo.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,friday.tw,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,ftchinese.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,ftimg.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,gate.io,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,getlantern.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,getsync.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,globalvoices.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,goo.ne.jp,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,goodreads.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,gov,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,gov.tw,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,greatfire.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,gumroad.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,hbg.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,heroku.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,hightail.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,hk01.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,hkbf.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,hkbookcity.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,hkej.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,hket.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,hkgolden.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,hootsuite.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,hudson.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,hyread.com.tw,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,ibtimes.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,i-cable.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,icij.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,icoco.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,imgur.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,initiummall.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,insecam.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,ipfs.io,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,issuu.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,istockphoto.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,japantimes.co.jp,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,jiji.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,jinx.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,jkforum.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,joinmastodon.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,justmysocks.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,justpaste.it,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,kakao.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,kakaocorp.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,kik.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,kobo.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,kobobooks.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,kodingen.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,lemonde.fr,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,lepoint.fr,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,lihkg.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,listennotes.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,livestream.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,logmein.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,mail.ru,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,mailchimp.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,marc.info,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,matters.news,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,maying.co,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,medium.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,mega.nz,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,mil,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,mingpao.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,mobile01.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,myspace.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,myspacecdn.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,nanyang.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,naver.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,neowin.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,newstapa.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,nexitally.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,nhk.or.jp,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,nicovideo.jp,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,nii.ac.jp,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,nikkei.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,nofile.io,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,now.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,nrk.no,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,nyt.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,nytchina.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,nytcn.me,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,nytco.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,nytimes.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,nytimg.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,nytlog.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,nytstyle.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,ok.ru,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,okex.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,on.cc,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,orientaldaily.com.my,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,overcast.fm,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,paltalk.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,pao-pao.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,parsevideo.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,pbxes.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,pcdvd.com.tw,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,pchome.com.tw,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,pcloud.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,picacomic.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,pinimg.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,pixiv.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,player.fm,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,plurk.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,po18.tw,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,potato.im,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,potatso.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,prism-break.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,proxifier.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,pt.im,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,pts.org.tw,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,pubu.com.tw,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,pubu.tw,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,pureapk.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,quora.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,quoracdn.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,rakuten.co.jp,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,readingtimes.com.tw,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,readmoo.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,redbubble.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,reddit.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,redditmedia.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,resilio.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,reuters.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,reutersmedia.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,rfi.fr,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,rixcloud.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,roadshow.hk,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,scmp.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,scribd.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,seatguru.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,shadowsocks.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,shopee.tw,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,slideshare.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,softfamous.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,soundcloud.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,ssrcloud.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,startpage.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,steamcommunity.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,steemit.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,steemitwallet.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,t66y.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,tapatalk.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,teco-hk.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,teco-mo.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,teddysun.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,textnow.me,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,theguardian.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,theinitium.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,thetvdb.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,tineye.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,torproject.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,tumblr.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,turbobit.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,tutanota.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,tvboxnow.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,udn.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,unseen.is,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,upmedia.mg,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,uptodown.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,urbandictionary.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,ustream.tv,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,uwants.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,v2ray.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,viber.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,videopress.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,vimeo.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,voachinese.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,voanews.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,voxer.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,vzw.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,w3schools.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,washingtonpost.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,wattpad.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,whoer.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,wikimapia.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,wikipedia.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,wikiquote.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,wikiwand.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,winudf.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,wire.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,wordpress.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,workflow.is,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,worldcat.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,wsj.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,wsj.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,xhamster.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,xn--90wwvt03e.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,xn--i2ru8q2qg.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,xnxx.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,xvideos.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,yahoo.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,yandex.ru,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,ycombinator.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,yesasia.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,yes-news.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,yomiuri.co.jp,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,you-get.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,zaobao.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,zb.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,zello.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,zeronet.io,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,zoom.us,🔰Зарубежный трафик",
    "DOMAIN-KEYWORD,github,🔰Зарубежный трафик",
    "DOMAIN-KEYWORD,jav,🔰Зарубежный трафик",
    "DOMAIN-KEYWORD,pinterest,🔰Зарубежный трафик",
    "DOMAIN-KEYWORD,porn,🔰Зарубежный трафик",
    "DOMAIN-KEYWORD,wikileaks,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,apartmentratings.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,apartments.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,bankmobilevibe.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,bing.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,booktopia.com.au,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,cccat.io,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,centauro.com.br,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,clearsurance.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,costco.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,crackle.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,depositphotos.cn,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,dish.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,dmm.co.jp,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,dmm.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,dnvod.tv,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,esurance.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,extmatrix.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,fastpic.ru,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,flipboard.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,fnac.be,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,fnac.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,funkyimg.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,fxnetworks.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,gettyimages.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,go.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,here.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,jcpenney.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,jiehua.tv,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,mailfence.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,nationwide.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,nbc.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,nexon.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,nordstrom.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,nordstromimage.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,nordstromrack.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,superpages.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,target.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,thinkgeek.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,tracfone.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,unity3d.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,uploader.jp,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,vevo.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,viu.tv,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,vk.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,vsco.co,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,xfinity.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,zattoo.com,🔰Зарубежный трафик",
    "DOMAIN,testflight.apple.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,appsto.re,🔰Зарубежный трафик",
    "DOMAIN,books.itunes.apple.com,🔰Зарубежный трафик",
    "DOMAIN,hls.itunes.apple.com,🔰Зарубежный трафик",
    "DOMAIN,apps.apple.com,🔰Зарубежный трафик",
    "DOMAIN,itunes.apple.com,🔰Зарубежный трафик",
    "DOMAIN,api-glb-sea.smoot.apple.com,🔰Зарубежный трафик",
    "DOMAIN,lookup-api.apple.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,abc.xyz,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,android.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,androidify.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,dialogflow.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,autodraw.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,capitalg.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,certificate-transparency.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,chrome.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,chromeexperiments.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,chromestatus.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,chromium.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,creativelab5.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,debug.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,deepmind.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,firebaseio.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,getmdl.io,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,ggpht.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,gmail.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,gmodules.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,godoc.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,golang.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,gstatic.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,gv.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,gwtproject.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,itasoftware.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,madewithcode.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,material.io,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,polymer-project.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,admin.recaptcha.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,recaptcha.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,shattered.io,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,synergyse.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,tensorflow.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,tfhub.dev,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,tiltbrush.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,waveprotocol.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,waymo.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,webmproject.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,webrtc.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,whatbrowser.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,widevine.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,x.company,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,youtu.be,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,yt.be,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,ytimg.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,1drv.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,1drv.ms,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,blob.core.windows.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,livefilestore.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,onedrive.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,storage.live.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,storage.msn.com,🔰Зарубежный трафик",
    "DOMAIN,oneclient.sfx.ms,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,0rz.tw,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,4bluestones.biz,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,9bis.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,allconnected.co,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,aol.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,bcc.com.tw,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,bit.ly,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,bitshare.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,blog.jp,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,blogimg.jp,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,blogtd.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,broadcast.co.nz,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,camfrog.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,cfos.de,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,citypopulation.de,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,cloudfront.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,ctitv.com.tw,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,cuhk.edu.hk,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,cusu.hk,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,discord.gg,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,discuss.com.hk,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,dropboxapi.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,duolingo.cn,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,edditstatic.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,flickriver.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,focustaiwan.tw,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,free.fr,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,gigacircle.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,hk-pub.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,hosting.co.uk,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,hwcdn.net,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,ifixit.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,iphone4hongkong.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,iphonetaiwan.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,iptvbin.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,linksalpha.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,manyvids.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,myactimes.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,newsblur.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,now.im,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,nowe.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,redditlist.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,s3.amazonaws.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,signal.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,smartmailcloud.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,sparknotes.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,streetvoice.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,supertop.co,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,tv.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,typepad.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,udnbkk.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,urbanairship.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,whispersystems.org,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,wikia.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,wn.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,wolframalpha.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,x-art.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,yimg.com,🔰Зарубежный трафик",
    "DOMAIN,api.steampowered.com,🔰Зарубежный трафик",
    "DOMAIN,store.steampowered.com,🔰Зарубежный трафик",
    "DOMAIN-SUFFIX,aaplimg.com,🍎Сервисы Apple",
    "DOMAIN-SUFFIX,apple.co,🍎Сервисы Apple",
    "DOMAIN-SUFFIX,apple.com,🍎Сервисы Apple",
    "DOMAIN-SUFFIX,apple-cloudkit.com,🍎Сервисы Apple",
    "DOMAIN-SUFFIX,appstore.com,🍎Сервисы Apple",
    "DOMAIN-SUFFIX,cdn-apple.com,🍎Сервисы Apple",
    "DOMAIN-SUFFIX,crashlytics.com,🍎Сервисы Apple",
    "DOMAIN-SUFFIX,icloud.com,🍎Сервисы Apple",
    "DOMAIN-SUFFIX,icloud-content.com,🍎Сервисы Apple",
    "DOMAIN-SUFFIX,me.com,🍎Сервисы Apple",
    "DOMAIN-SUFFIX,mzstatic.com,🍎Сервисы Apple",
    "DOMAIN,www-cdn.icloud.com.akadns.net,🍎Сервисы Apple",
    "DOMAIN-SUFFIX,t.me,✈️Telegram",
    "DOMAIN-SUFFIX,tdesktop.com,✈️Telegram",
    "DOMAIN-SUFFIX,telegra.ph,✈️Telegram",
    "DOMAIN-SUFFIX,telegram.me,✈️Telegram",
    "DOMAIN-SUFFIX,telegram.org,✈️Telegram",
    "IP-CIDR,91.108.4.0/22,✈️Telegram,no-resolve",
    "IP-CIDR,91.108.8.0/22,✈️Telegram,no-resolve",
    "IP-CIDR,91.108.12.0/22,✈️Telegram,no-resolve",
    "IP-CIDR,91.108.16.0/22,✈️Telegram,no-resolve",
    "IP-CIDR,91.108.56.0/22,✈️Telegram,no-resolve",
    "IP-CIDR,149.154.160.0/20,✈️Telegram,no-resolve",
    "IP-CIDR6,2001:b28:f23d::/48,✈️Telegram,no-resolve",
    "IP-CIDR6,2001:b28:f23f::/48,✈️Telegram,no-resolve",
    "IP-CIDR6,2001:67c:4e8::/48,✈️Telegram,no-resolve",
    "DOMAIN-SUFFIX,googlevideo.com,🎬Youtube",
    "DOMAIN-SUFFIX,youtube.com,🎬Youtube",
    "DOMAIN,youtubei.googleapis.com,🎬Youtube",
    "DOMAIN-SUFFIX,netflix.com,🎬Netflix",
    "DOMAIN-SUFFIX,netflix.net,🎬Netflix",
    "DOMAIN-SUFFIX,nflxext.com,🎬Netflix",
    "DOMAIN-SUFFIX,nflximg.com,🎬Netflix",
    "DOMAIN-SUFFIX,nflximg.net,🎬Netflix",
    "DOMAIN-SUFFIX,nflxso.net,🎬Netflix",
    "DOMAIN-SUFFIX,nflxvideo.net,🎬Netflix",
    "DOMAIN-SUFFIX,netflixdnstest0.com,🎬Netflix",
    "DOMAIN-SUFFIX,netflixdnstest1.com,🎬Netflix",
    "DOMAIN-SUFFIX,netflixdnstest2.com,🎬Netflix",
    "DOMAIN-SUFFIX,netflixdnstest3.com,🎬Netflix",
    "DOMAIN-SUFFIX,netflixdnstest4.com,🎬Netflix",
    "DOMAIN-SUFFIX,netflixdnstest5.com,🎬Netflix",
    "DOMAIN-SUFFIX,netflixdnstest6.com,🎬Netflix",
    "DOMAIN-SUFFIX,netflixdnstest7.com,🎬Netflix",
    "DOMAIN-SUFFIX,netflixdnstest8.com,🎬Netflix",
    "DOMAIN-SUFFIX,netflixdnstest9.com,🎬Netflix",
    "IP-CIDR,23.246.0.0/18,🎬Netflix,no-resolve",
    "IP-CIDR,37.77.184.0/21,🎬Netflix,no-resolve",
    "IP-CIDR,45.57.0.0/17,🎬Netflix,no-resolve",
    "IP-CIDR,64.120.128.0/17,🎬Netflix,no-resolve",
    "IP-CIDR,66.197.128.0/17,🎬Netflix,no-resolve",
    "IP-CIDR,108.175.32.0/20,🎬Netflix,no-resolve",
    "IP-CIDR,192.173.64.0/18,🎬Netflix,no-resolve",
    "IP-CIDR,198.38.96.0/19,🎬Netflix,no-resolve",
    "IP-CIDR,198.45.48.0/20,🎬Netflix,no-resolve",
    "DOMAIN-SUFFIX,deezer.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,dzcdn.net,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,kkbox.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,kkbox.com.tw,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,kfs.io,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,joox.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,pandora.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,p-cdn.us,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,sndcdn.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,soundcloud.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,pscdn.co,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,scdn.co,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,spotify.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,spoti.fi,🎬Иностранные СМИ",
    "DOMAIN-KEYWORD,spotify.com,🎬Иностранные СМИ",
    "DOMAIN-KEYWORD,-spotify-com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,tidal.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,c4assets.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,channel4.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,abema.io,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,ameba.jp,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,abema.tv,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,hayabusa.io,🎬Иностранные СМИ",
    "DOMAIN,abematv.akamaized.net,🎬Иностранные СМИ",
    "DOMAIN,ds-linear-abematv.akamaized.net,🎬Иностранные СМИ",
    "DOMAIN,ds-vod-abematv.akamaized.net,🎬Иностранные СМИ",
    "DOMAIN,linear-abematv.akamaized.net,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,aiv-cdn.net,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,aiv-delivery.net,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,amazonvideo.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,primevideo.com,🎬Иностранные СМИ",
    "DOMAIN,avodmp4s3ww-a.akamaihd.net,🎬Иностранные СМИ",
    "DOMAIN,d25xi40x97liuc.cloudfront.net,🎬Иностранные СМИ",
    "DOMAIN,dmqdd6hw24ucf.cloudfront.net,🎬Иностранные СМИ",
    "DOMAIN,d22qjgkvxw22r6.cloudfront.net,🎬Иностранные СМИ",
    "DOMAIN,d1v5ir2lpwr8os.cloudfront.net,🎬Иностранные СМИ",
    "DOMAIN-KEYWORD,avoddashs,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,bahamut.com.tw,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,gamer.com.tw,🎬Иностранные СМИ",
    "DOMAIN,gamer-cds.cdn.hinet.net,🎬Иностранные СМИ",
    "DOMAIN,gamer2-cds.cdn.hinet.net,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,bbc.co.uk,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,bbci.co.uk,🎬Иностранные СМИ",
    "DOMAIN-KEYWORD,bbcfmt,🎬Иностранные СМИ",
    "DOMAIN-KEYWORD,uk-live,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,dazn.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,dazn-api.com,🎬Иностранные СМИ",
    "DOMAIN,d151l6v8er5bdm.cloudfront.net,🎬Иностранные СМИ",
    "DOMAIN-KEYWORD,voddazn,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,bamgrid.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,disney-plus.net,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,disneyplus.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,dssott.com,🎬Иностранные СМИ",
    "DOMAIN,cdn.registerdisney.go.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,encoretvb.com,🎬Иностранные СМИ",
    "DOMAIN,edge.api.brightcove.com,🎬Иностранные СМИ",
    "DOMAIN,bcbolt446c5271-a.akamaihd.net,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,fox.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,foxdcg.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,theplatform.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,uplynk.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,hbo.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,hbogo.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,hbonow.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,hbogoasia.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,hbogoasia.hk,🎬Иностранные СМИ",
    "DOMAIN,bcbolthboa-a.akamaihd.net,🎬Иностранные СМИ",
    "DOMAIN,players.brightcove.net,🎬Иностранные СМИ",
    "DOMAIN,s3-ap-southeast-1.amazonaws.com,🎬Иностранные СМИ",
    "DOMAIN,dai3fd1oh325y.cloudfront.net,🎬Иностранные СМИ",
    "DOMAIN,44wilhpljf.execute-api.ap-southeast-1.amazonaws.com,🎬Иностранные СМИ",
    "DOMAIN,hboasia1-i.akamaihd.net,🎬Иностранные СМИ",
    "DOMAIN,hboasia2-i.akamaihd.net,🎬Иностранные СМИ",
    "DOMAIN,hboasia3-i.akamaihd.net,🎬Иностранные СМИ",
    "DOMAIN,hboasia4-i.akamaihd.net,🎬Иностранные СМИ",
    "DOMAIN,hboasia5-i.akamaihd.net,🎬Иностранные СМИ",
    "DOMAIN,cf-images.ap-southeast-1.prod.boltdns.net,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,5itv.tv,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,ocnttv.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,hulu.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,huluim.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,hulustream.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,happyon.jp,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,hulu.jp,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,itv.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,itvstatic.com,🎬Иностранные СМИ",
    "DOMAIN,itvpnpmobile-a.akamaihd.net,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,kktv.com.tw,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,kktv.me,🎬Иностранные СМИ",
    "DOMAIN,kktv-theater.kk.stream,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,linetv.tw,🎬Иностранные СМИ",
    "DOMAIN,d3c7rimkq79yfu.cloudfront.net,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,litv.tv,🎬Иностранные СМИ",
    "DOMAIN,litvfreemobile-hichannel.cdn.hinet.net,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,channel5.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,my5.tv,🎬Иностранные СМИ",
    "DOMAIN,d349g9zuie06uo.cloudfront.net,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,mytvsuper.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,tvb.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,netflix.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,netflix.net,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,nflxext.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,nflximg.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,nflximg.net,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,nflxso.net,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,nflxvideo.net,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,netflixdnstest0.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,netflixdnstest1.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,netflixdnstest2.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,netflixdnstest3.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,netflixdnstest4.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,netflixdnstest5.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,netflixdnstest6.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,netflixdnstest7.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,netflixdnstest8.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,netflixdnstest9.com,🎬Иностранные СМИ",
    "IP-CIDR,23.246.0.0/18,🎬Иностранные СМИ,no-resolve",
    "IP-CIDR,37.77.184.0/21,🎬Иностранные СМИ,no-resolve",
    "IP-CIDR,45.57.0.0/17,🎬Иностранные СМИ,no-resolve",
    "IP-CIDR,64.120.128.0/17,🎬Иностранные СМИ,no-resolve",
    "IP-CIDR,66.197.128.0/17,🎬Иностранные СМИ,no-resolve",
    "IP-CIDR,108.175.32.0/20,🎬Иностранные СМИ,no-resolve",
    "IP-CIDR,192.173.64.0/18,🎬Иностранные СМИ,no-resolve",
    "IP-CIDR,198.38.96.0/19,🎬Иностранные СМИ,no-resolve",
    "IP-CIDR,198.45.48.0/20,🎬Иностранные СМИ,no-resolve",
    "DOMAIN-SUFFIX,dmc.nico,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,nicovideo.jp,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,nimg.jp,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,socdm.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,pbs.org,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,phncdn.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,pornhub.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,pornhubpremium.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,skyking.com.tw,🎬Иностранные СМИ",
    "DOMAIN,hamifans.emome.net,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,twitch.tv,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,twitchcdn.net,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,ttvnw.net,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,jtvnw.net,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,viu.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,viu.tv,🎬Иностранные СМИ",
    "DOMAIN,api.viu.now.com,🎬Иностранные СМИ",
    "DOMAIN,d1k2us671qcoau.cloudfront.net,🎬Иностранные СМИ",
    "DOMAIN,d2anahhhmp1ffz.cloudfront.net,🎬Иностранные СМИ",
    "DOMAIN,dfp6rglgjqszk.cloudfront.net,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,googlevideo.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,youtube.com,🎬Иностранные СМИ",
    "DOMAIN,youtubei.googleapis.com,🎬Иностранные СМИ",
    "DOMAIN-SUFFIX,local,DIRECT",
    "IP-CIDR,192.168.0.0/16,DIRECT,no-resolve",
    "IP-CIDR,10.0.0.0/8,DIRECT,no-resolve",
    "IP-CIDR,172.16.0.0/12,DIRECT,no-resolve",
    "IP-CIDR,127.0.0.0/8,DIRECT,no-resolve",
    "IP-CIDR,100.64.0.0/10,DIRECT,no-resolve",
    "IP-CIDR6,::1/128,DIRECT,no-resolve",
    "IP-CIDR6,fc00::/7,DIRECT,no-resolve",
    "IP-CIDR6,fe80::/10,DIRECT,no-resolve",
    "IP-CIDR6,fd00::/8,DIRECT,no-resolve",
    "DOMAIN,app.adjust.com,DIRECT",
    "DOMAIN-SUFFIX,googletraveladservices.com,DIRECT",
    "DOMAIN,dl.google.com,DIRECT",
    "DOMAIN,mtalk.google.com,DIRECT",
    "DOMAIN,livew.l.qq.com,DIRECT",
    "DOMAIN,vd.l.qq.com,DIRECT",
    "DOMAIN,analytics.strava.com,DIRECT",
    "DOMAIN,msg.umeng.com,DIRECT",
    "DOMAIN,msg.umengcloud.com,DIRECT",
    "DOMAIN-SUFFIX,qhres.com,DIRECT",
    "DOMAIN-SUFFIX,qhimg.com,DIRECT",
    "DOMAIN-SUFFIX,akadns.net,DIRECT",
    "DOMAIN-SUFFIX,alibaba.com,DIRECT",
    "DOMAIN-SUFFIX,alicdn.com,DIRECT",
    "DOMAIN-SUFFIX,alikunlun.com,DIRECT",
    "DOMAIN-SUFFIX,alipay.com,DIRECT",
    "DOMAIN-SUFFIX,amap.com,DIRECT",
    "DOMAIN-SUFFIX,autonavi.com,DIRECT",
    "DOMAIN-SUFFIX,dingtalk.com,DIRECT",
    "DOMAIN-SUFFIX,mxhichina.com,DIRECT",
    "DOMAIN-SUFFIX,soku.com,DIRECT",
    "DOMAIN-SUFFIX,taobao.com,DIRECT",
    "DOMAIN-SUFFIX,tmall.com,DIRECT",
    "DOMAIN-SUFFIX,tmall.hk,DIRECT",
    "DOMAIN-SUFFIX,ykimg.com,DIRECT",
    "DOMAIN-SUFFIX,youku.com,DIRECT",
    "DOMAIN-SUFFIX,xiami.com,DIRECT",
    "DOMAIN-SUFFIX,xiami.net,DIRECT",
    "DOMAIN-SUFFIX,aaplimg.com,DIRECT",
    "DOMAIN-SUFFIX,apple.co,DIRECT",
    "DOMAIN-SUFFIX,apple.com,DIRECT",
    "DOMAIN-SUFFIX,apple-cloudkit.com,DIRECT",
    "DOMAIN-SUFFIX,appstore.com,DIRECT",
    "DOMAIN-SUFFIX,cdn-apple.com,DIRECT",
    "DOMAIN-SUFFIX,crashlytics.com,DIRECT",
    "DOMAIN-SUFFIX,icloud.com,DIRECT",
    "DOMAIN-SUFFIX,icloud-content.com,DIRECT",
    "DOMAIN-SUFFIX,me.com,DIRECT",
    "DOMAIN-SUFFIX,mzstatic.com,DIRECT",
    "DOMAIN,www-cdn.icloud.com.akadns.net,DIRECT",
    "DOMAIN-SUFFIX,baidu.com,DIRECT",
    "DOMAIN-SUFFIX,baidubcr.com,DIRECT",
    "DOMAIN-SUFFIX,bdstatic.com,DIRECT",
    "DOMAIN-SUFFIX,yunjiasu-cdn.net,DIRECT",
    "DOMAIN-SUFFIX,acgvideo.com,DIRECT",
    "DOMAIN-SUFFIX,biliapi.com,DIRECT",
    "DOMAIN-SUFFIX,biliapi.net,DIRECT",
    "DOMAIN-SUFFIX,bilibili.com,DIRECT",
    "DOMAIN-SUFFIX,bilibili.tv,DIRECT",
    "DOMAIN-SUFFIX,bilivideo.com,DIRECT",
    "DOMAIN-SUFFIX,hdslb.com,DIRECT",
    "DOMAIN-SUFFIX,blizzard.com,DIRECT",
    "DOMAIN-SUFFIX,battle.net,DIRECT",
    "DOMAIN,blzddist1-a.akamaihd.net,DIRECT",
    "DOMAIN-SUFFIX,feiliao.com,DIRECT",
    "DOMAIN-SUFFIX,pstatp.com,DIRECT",
    "DOMAIN-SUFFIX,snssdk.com,DIRECT",
    "DOMAIN-SUFFIX,iesdouyin.com,DIRECT",
    "DOMAIN-SUFFIX,toutiao.com,DIRECT",
    "DOMAIN-SUFFIX,cctv.com,DIRECT",
    "DOMAIN-SUFFIX,cctvpic.com,DIRECT",
    "DOMAIN-SUFFIX,livechina.com,DIRECT",
    "DOMAIN-SUFFIX,didialift.com,DIRECT",
    "DOMAIN-SUFFIX,didiglobal.com,DIRECT",
    "DOMAIN-SUFFIX,udache.com,DIRECT",
    "DOMAIN-SUFFIX,343480.com,DIRECT",
    "DOMAIN-SUFFIX,baduziyuan.com,DIRECT",
    "DOMAIN-SUFFIX,com-hs-hkdy.com,DIRECT",
    "DOMAIN-SUFFIX,czybjz.com,DIRECT",
    "DOMAIN-SUFFIX,dandanzan.com,DIRECT",
    "DOMAIN-SUFFIX,fjhps.com,DIRECT",
    "DOMAIN-SUFFIX,kuyunbo.club,DIRECT",
    "DOMAIN-SUFFIX,21cn.com,DIRECT",
    "DOMAIN-SUFFIX,hitv.com,DIRECT",
    "DOMAIN-SUFFIX,mgtv.com,DIRECT",
    "DOMAIN-SUFFIX,iqiyi.com,DIRECT",
    "DOMAIN-SUFFIX,iqiyipic.com,DIRECT",
    "DOMAIN-SUFFIX,71.am.com,DIRECT",
    "DOMAIN-SUFFIX,jd.com,DIRECT",
    "DOMAIN-SUFFIX,jd.hk,DIRECT",
    "DOMAIN-SUFFIX,jdpay.com,DIRECT",
    "DOMAIN-SUFFIX,360buyimg.com,DIRECT",
    "DOMAIN-SUFFIX,iciba.com,DIRECT",
    "DOMAIN-SUFFIX,ksosoft.com,DIRECT",
    "DOMAIN-SUFFIX,meitu.com,DIRECT",
    "DOMAIN-SUFFIX,meitudata.com,DIRECT",
    "DOMAIN-SUFFIX,meitustat.com,DIRECT",
    "DOMAIN-SUFFIX,meipai.com,DIRECT",
    "DOMAIN-SUFFIX,duokan.com,DIRECT",
    "DOMAIN-SUFFIX,mi-img.com,DIRECT",
    "DOMAIN-SUFFIX,miui.com,DIRECT",
    "DOMAIN-SUFFIX,miwifi.com,DIRECT",
    "DOMAIN-SUFFIX,xiaomi.com,DIRECT",
    "DOMAIN-SUFFIX,microsoft.com,DIRECT",
    "DOMAIN-SUFFIX,msecnd.net,DIRECT",
    "DOMAIN-SUFFIX,office365.com,DIRECT",
    "DOMAIN-SUFFIX,outlook.com,DIRECT",
    "DOMAIN-SUFFIX,s-microsoft.com,DIRECT",
    "DOMAIN-SUFFIX,visualstudio.com,DIRECT",
    "DOMAIN-SUFFIX,windows.com,DIRECT",
    "DOMAIN-SUFFIX,windowsupdate.com,DIRECT",
    "DOMAIN,officecdn-microsoft-com.akamaized.net,DIRECT",
    "DOMAIN-SUFFIX,163.com,DIRECT",
    "DOMAIN-SUFFIX,126.net,DIRECT",
    "DOMAIN-SUFFIX,127.net,DIRECT",
    "DOMAIN-SUFFIX,163yun.com,DIRECT",
    "DOMAIN-SUFFIX,lofter.com,DIRECT",
    "DOMAIN-SUFFIX,netease.com,DIRECT",
    "DOMAIN-SUFFIX,ydstatic.com,DIRECT",
    "DOMAIN-SUFFIX,sina.com,DIRECT",
    "DOMAIN-SUFFIX,weibo.com,DIRECT",
    "DOMAIN-SUFFIX,weibocdn.com,DIRECT",
    "DOMAIN-SUFFIX,sohu.com,DIRECT",
    "DOMAIN-SUFFIX,sohucs.com,DIRECT",
    "DOMAIN-SUFFIX,sohu-inc.com,DIRECT",
    "DOMAIN-SUFFIX,v-56.com,DIRECT",
    "DOMAIN-SUFFIX,sogo.com,DIRECT",
    "DOMAIN-SUFFIX,sogou.com,DIRECT",
    "DOMAIN-SUFFIX,sogoucdn.com,DIRECT",
    "DOMAIN-SUFFIX,steampowered.com,DIRECT",
    "DOMAIN-SUFFIX,steam-chat.com,DIRECT",
    "DOMAIN-SUFFIX,steamgames.com,DIRECT",
    "DOMAIN-SUFFIX,steamusercontent.com,DIRECT",
    "DOMAIN-SUFFIX,steamcontent.com,DIRECT",
    "DOMAIN-SUFFIX,steamstatic.com,DIRECT",
    "DOMAIN-SUFFIX,steamcdn-a.akamaihd.net,DIRECT",
    "DOMAIN-SUFFIX,steamstat.us,DIRECT",
    "DOMAIN-SUFFIX,gtimg.com,DIRECT",
    "DOMAIN-SUFFIX,idqqimg.com,DIRECT",
    "DOMAIN-SUFFIX,igamecj.com,DIRECT",
    "DOMAIN-SUFFIX,myapp.com,DIRECT",
    "DOMAIN-SUFFIX,myqcloud.com,DIRECT",
    "DOMAIN-SUFFIX,qq.com,DIRECT",
    "DOMAIN-SUFFIX,tencent.com,DIRECT",
    "DOMAIN-SUFFIX,tencent-cloud.net,DIRECT",
    "DOMAIN-SUFFIX,jstucdn.com,DIRECT",
    "DOMAIN-SUFFIX,zimuzu.io,DIRECT",
    "DOMAIN-SUFFIX,zimuzu.tv,DIRECT",
    "DOMAIN-SUFFIX,zmz2019.com,DIRECT",
    "DOMAIN-SUFFIX,zmzapi.com,DIRECT",
    "DOMAIN-SUFFIX,zmzapi.net,DIRECT",
    "DOMAIN-SUFFIX,zmzfile.com,DIRECT",
    "DOMAIN-SUFFIX,ccgslb.com,DIRECT",
    "DOMAIN-SUFFIX,ccgslb.net,DIRECT",
    "DOMAIN-SUFFIX,chinanetcenter.com,DIRECT",
    "DOMAIN-SUFFIX,meixincdn.com,DIRECT",
    "DOMAIN-SUFFIX,ourdvs.com,DIRECT",
    "DOMAIN-SUFFIX,staticdn.net,DIRECT",
    "DOMAIN-SUFFIX,wangsu.com,DIRECT",
    "DOMAIN-SUFFIX,ipip.net,DIRECT",
    "DOMAIN-SUFFIX,ip.la,DIRECT",
    "DOMAIN-SUFFIX,ip-cdn.com,DIRECT",
    "DOMAIN-SUFFIX,ipv6-test.com,DIRECT",
    "DOMAIN-SUFFIX,test-ipv6.com,DIRECT",
    "DOMAIN-SUFFIX,whatismyip.com,DIRECT",
    "DOMAIN-SUFFIX,netspeedtestmaster.com,DIRECT",
    "DOMAIN,speedtest.macpaw.com,DIRECT",
    "DOMAIN-SUFFIX,awesome-hd.me,DIRECT",
    "DOMAIN-SUFFIX,broadcasthe.net,DIRECT",
    "DOMAIN-SUFFIX,chdbits.co,DIRECT",
    "DOMAIN-SUFFIX,classix-unlimited.co.uk,DIRECT",
    "DOMAIN-SUFFIX,empornium.me,DIRECT",
    "DOMAIN-SUFFIX,gazellegames.net,DIRECT",
    "DOMAIN-SUFFIX,hdchina.org,DIRECT",
    "DOMAIN-SUFFIX,hdsky.me,DIRECT",
    "DOMAIN-SUFFIX,icetorrent.org,DIRECT",
    "DOMAIN-SUFFIX,jpopsuki.eu,DIRECT",
    "DOMAIN-SUFFIX,keepfrds.com,DIRECT",
    "DOMAIN-SUFFIX,madsrevolution.net,DIRECT",
    "DOMAIN-SUFFIX,m-team.cc,DIRECT",
    "DOMAIN-SUFFIX,nanyangpt.com,DIRECT",
    "DOMAIN-SUFFIX,ncore.cc,DIRECT",
    "DOMAIN-SUFFIX,open.cd,DIRECT",
    "DOMAIN-SUFFIX,ourbits.club,DIRECT",
    "DOMAIN-SUFFIX,passthepopcorn.me,DIRECT",
    "DOMAIN-SUFFIX,privatehd.to,DIRECT",
    "DOMAIN-SUFFIX,redacted.ch,DIRECT",
    "DOMAIN-SUFFIX,springsunday.net,DIRECT",
    "DOMAIN-SUFFIX,tjupt.org,DIRECT",
    "DOMAIN-SUFFIX,totheglory.im,DIRECT",
    "DOMAIN-SUFFIX,acm.org,DIRECT",
    "DOMAIN-SUFFIX,acs.org,DIRECT",
    "DOMAIN-SUFFIX,aip.org,DIRECT",
    "DOMAIN-SUFFIX,ams.org,DIRECT",
    "DOMAIN-SUFFIX,annualreviews.org,DIRECT",
    "DOMAIN-SUFFIX,aps.org,DIRECT",
    "DOMAIN-SUFFIX,ascelibrary.org,DIRECT",
    "DOMAIN-SUFFIX,asm.org,DIRECT",
    "DOMAIN-SUFFIX,asme.org,DIRECT",
    "DOMAIN-SUFFIX,astm.org,DIRECT",
    "DOMAIN-SUFFIX,bmj.com,DIRECT",
    "DOMAIN-SUFFIX,cambridge.org,DIRECT",
    "DOMAIN-SUFFIX,cas.org,DIRECT",
    "DOMAIN-SUFFIX,clarivate.com,DIRECT",
    "DOMAIN-SUFFIX,ebscohost.com,DIRECT",
    "DOMAIN-SUFFIX,emerald.com,DIRECT",
    "DOMAIN-SUFFIX,engineeringvillage.com,DIRECT",
    "DOMAIN-SUFFIX,icevirtuallibrary.com,DIRECT",
    "DOMAIN-SUFFIX,ieee.org,DIRECT",
    "DOMAIN-SUFFIX,imf.org,DIRECT",
    "DOMAIN-SUFFIX,iop.org,DIRECT",
    "DOMAIN-SUFFIX,jamanetwork.com,DIRECT",
    "DOMAIN-SUFFIX,jhu.edu,DIRECT",
    "DOMAIN-SUFFIX,jstor.org,DIRECT",
    "DOMAIN-SUFFIX,karger.com,DIRECT",
    "DOMAIN-SUFFIX,libguides.com,DIRECT",
    "DOMAIN-SUFFIX,madsrevolution.net,DIRECT",
    "DOMAIN-SUFFIX,mpg.de,DIRECT",
    "DOMAIN-SUFFIX,myilibrary.com,DIRECT",
    "DOMAIN-SUFFIX,nature.com,DIRECT",
    "DOMAIN-SUFFIX,oecd-ilibrary.org,DIRECT",
    "DOMAIN-SUFFIX,osapublishing.org,DIRECT",
    "DOMAIN-SUFFIX,oup.com,DIRECT",
    "DOMAIN-SUFFIX,ovid.com,DIRECT",
    "DOMAIN-SUFFIX,oxfordartonline.com,DIRECT",
    "DOMAIN-SUFFIX,oxfordbibliographies.com,DIRECT",
    "DOMAIN-SUFFIX,oxfordmusiconline.com,DIRECT",
    "DOMAIN-SUFFIX,pnas.org,DIRECT",
    "DOMAIN-SUFFIX,proquest.com,DIRECT",
    "DOMAIN-SUFFIX,rsc.org,DIRECT",
    "DOMAIN-SUFFIX,sagepub.com,DIRECT",
    "DOMAIN-SUFFIX,sciencedirect.com,DIRECT",
    "DOMAIN-SUFFIX,sciencemag.org,DIRECT",
    "DOMAIN-SUFFIX,scopus.com,DIRECT",
    "DOMAIN-SUFFIX,siam.org,DIRECT",
    "DOMAIN-SUFFIX,spiedigitallibrary.org,DIRECT",
    "DOMAIN-SUFFIX,springer.com,DIRECT",
    "DOMAIN-SUFFIX,springerlink.com,DIRECT",
    "DOMAIN-SUFFIX,tandfonline.com,DIRECT",
    "DOMAIN-SUFFIX,un.org,DIRECT",
    "DOMAIN-SUFFIX,uni-bielefeld.de,DIRECT",
    "DOMAIN-SUFFIX,webofknowledge.com,DIRECT",
    "DOMAIN-SUFFIX,westlaw.com,DIRECT",
    "DOMAIN-SUFFIX,wiley.com,DIRECT",
    "DOMAIN-SUFFIX,worldbank.org,DIRECT",
    "DOMAIN-SUFFIX,worldscientific.com,DIRECT",
    "DOMAIN-SUFFIX,cn,DIRECT",
    "DOMAIN-SUFFIX,360in.com,DIRECT",
    "DOMAIN-SUFFIX,51ym.me,DIRECT",
    "DOMAIN-SUFFIX,8686c.com,DIRECT",
    "DOMAIN-SUFFIX,abchina.com,DIRECT",
    "DOMAIN-SUFFIX,accuweather.com,DIRECT",
    "DOMAIN-SUFFIX,aicoinstorge.com,DIRECT",
    "DOMAIN-SUFFIX,air-matters.com,DIRECT",
    "DOMAIN-SUFFIX,air-matters.io,DIRECT",
    "DOMAIN-SUFFIX,aixifan.com,DIRECT",
    "DOMAIN-SUFFIX,amd.com,DIRECT",
    "DOMAIN-SUFFIX,b612.net,DIRECT",
    "DOMAIN-SUFFIX,bdatu.com,DIRECT",
    "DOMAIN-SUFFIX,beitaichufang.com,DIRECT",
    "DOMAIN-SUFFIX,bjango.com,DIRECT",
    "DOMAIN-SUFFIX,booking.com,DIRECT",
    "DOMAIN-SUFFIX,bstatic.com,DIRECT",
    "DOMAIN-SUFFIX,cailianpress.com,DIRECT",
    "DOMAIN-SUFFIX,camera360.com,DIRECT",
    "DOMAIN-SUFFIX,chinaso.com,DIRECT",
    "DOMAIN-SUFFIX,chua.pro,DIRECT",
    "DOMAIN-SUFFIX,chuimg.com,DIRECT",
    "DOMAIN-SUFFIX,chunyu.mobi,DIRECT",
    "DOMAIN-SUFFIX,chushou.tv,DIRECT",
    "DOMAIN-SUFFIX,cmbchina.com,DIRECT",
    "DOMAIN-SUFFIX,cmbimg.com,DIRECT",
    "DOMAIN-SUFFIX,ctrip.com,DIRECT",
    "DOMAIN-SUFFIX,dfcfw.com,DIRECT",
    "DOMAIN-SUFFIX,docschina.org,DIRECT",
    "DOMAIN-SUFFIX,douban.com,DIRECT",
    "DOMAIN-SUFFIX,doubanio.com,DIRECT",
    "DOMAIN-SUFFIX,douyu.com,DIRECT",
    "DOMAIN-SUFFIX,dxycdn.com,DIRECT",
    "DOMAIN-SUFFIX,dytt8.net,DIRECT",
    "DOMAIN-SUFFIX,eastmoney.com,DIRECT",
    "DOMAIN-SUFFIX,eudic.net,DIRECT",
    "DOMAIN-SUFFIX,feng.com,DIRECT",
    "DOMAIN-SUFFIX,fengkongcloud.com,DIRECT",
    "DOMAIN-SUFFIX,frdic.com,DIRECT",
    "DOMAIN-SUFFIX,futu5.com,DIRECT",
    "DOMAIN-SUFFIX,futunn.com,DIRECT",
    "DOMAIN-SUFFIX,gandi.net,DIRECT",
    "DOMAIN-SUFFIX,geilicdn.com,DIRECT",
    "DOMAIN-SUFFIX,getpricetag.com,DIRECT",
    "DOMAIN-SUFFIX,gifshow.com,DIRECT",
    "DOMAIN-SUFFIX,godic.net,DIRECT",
    "DOMAIN-SUFFIX,hicloud.com,DIRECT",
    "DOMAIN-SUFFIX,hongxiu.com,DIRECT",
    "DOMAIN-SUFFIX,hostbuf.com,DIRECT",
    "DOMAIN-SUFFIX,huxiucdn.com,DIRECT",
    "DOMAIN-SUFFIX,huya.com,DIRECT",
    "DOMAIN-SUFFIX,infinitynewtab.com,DIRECT",
    "DOMAIN-SUFFIX,ithome.com,DIRECT",
    "DOMAIN-SUFFIX,java.com,DIRECT",
    "DOMAIN-SUFFIX,jidian.im,DIRECT",
    "DOMAIN-SUFFIX,kaiyanapp.com,DIRECT",
    "DOMAIN-SUFFIX,kaspersky-labs.com,DIRECT",
    "DOMAIN-SUFFIX,keepcdn.com,DIRECT",
    "DOMAIN-SUFFIX,kkmh.com,DIRECT",
    "DOMAIN-SUFFIX,licdn.com,DIRECT",
    "DOMAIN-SUFFIX,linkedin.com,DIRECT",
    "DOMAIN-SUFFIX,loli.net,DIRECT",
    "DOMAIN-SUFFIX,luojilab.com,DIRECT",
    "DOMAIN-SUFFIX,maoyan.com,DIRECT",
    "DOMAIN-SUFFIX,maoyun.tv,DIRECT",
    "DOMAIN-SUFFIX,meituan.com,DIRECT",
    "DOMAIN-SUFFIX,meituan.net,DIRECT",
    "DOMAIN-SUFFIX,mobike.com,DIRECT",
    "DOMAIN-SUFFIX,moke.com,DIRECT",
    "DOMAIN-SUFFIX,mubu.com,DIRECT",
    "DOMAIN-SUFFIX,myzaker.com,DIRECT",
    "DOMAIN-SUFFIX,nim-lang-cn.org,DIRECT",
    "DOMAIN-SUFFIX,nvidia.com,DIRECT",
    "DOMAIN-SUFFIX,oracle.com,DIRECT",
    "DOMAIN-SUFFIX,paypal.com,DIRECT",
    "DOMAIN-SUFFIX,paypalobjects.com,DIRECT",
    "DOMAIN-SUFFIX,qdaily.com,DIRECT",
    "DOMAIN-SUFFIX,qidian.com,DIRECT",
    "DOMAIN-SUFFIX,qyer.com,DIRECT",
    "DOMAIN-SUFFIX,qyerstatic.com,DIRECT",
    "DOMAIN-SUFFIX,raychase.net,DIRECT",
    "DOMAIN-SUFFIX,ronghub.com,DIRECT",
    "DOMAIN-SUFFIX,ruguoapp.com,DIRECT",
    "DOMAIN-SUFFIX,s-reader.com,DIRECT",
    "DOMAIN-SUFFIX,sankuai.com,DIRECT",
    "DOMAIN-SUFFIX,scomper.me,DIRECT",
    "DOMAIN-SUFFIX,seafile.com,DIRECT",
    "DOMAIN-SUFFIX,sm.ms,DIRECT",
    "DOMAIN-SUFFIX,smzdm.com,DIRECT",
    "DOMAIN-SUFFIX,snapdrop.net,DIRECT",
    "DOMAIN-SUFFIX,snwx.com,DIRECT",
    "DOMAIN-SUFFIX,sspai.com,DIRECT",
    "DOMAIN-SUFFIX,takungpao.com,DIRECT",
    "DOMAIN-SUFFIX,teamviewer.com,DIRECT",
    "DOMAIN-SUFFIX,tianyancha.com,DIRECT",
    "DOMAIN-SUFFIX,udacity.com,DIRECT",
    "DOMAIN-SUFFIX,uning.com,DIRECT",
    "DOMAIN-SUFFIX,vmware.com,DIRECT",
    "DOMAIN-SUFFIX,weather.com,DIRECT",
    "DOMAIN-SUFFIX,weico.cc,DIRECT",
    "DOMAIN-SUFFIX,weidian.com,DIRECT",
    "DOMAIN-SUFFIX,xiachufang.com,DIRECT",
    "DOMAIN-SUFFIX,ximalaya.com,DIRECT",
    "DOMAIN-SUFFIX,xinhuanet.com,DIRECT",
    "DOMAIN-SUFFIX,xmcdn.com,DIRECT",
    "DOMAIN-SUFFIX,yangkeduo.com,DIRECT",
    "DOMAIN-SUFFIX,zhangzishi.cc,DIRECT",
    "DOMAIN-SUFFIX,zhihu.com,DIRECT",
    "DOMAIN-SUFFIX,zhimg.com,DIRECT",
    "DOMAIN-SUFFIX,zhuihd.com,DIRECT",
    "DOMAIN,download.jetbrains.com,DIRECT",
    "DOMAIN,images-cn.ssl-images-amazon.com,DIRECT",
    "IP-CIDR,119.28.28.28/32,DIRECT,no-resolve",
    "GEOIP,CN,DIRECT",
    "MATCH,⚓️Другой трафик"
  ],
};
